config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects
  resources :users, only: %i[index edit destroy update]
  resources :bug_tickets do
    member do
      get 'versions', to: 'bug_tickets#versions'
    end
  end

  root to: 'welcome#home'

  get 'welcome/home'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/bug_ticket.rb
# frozen_string_literal: true

class BugTicket < ApplicationRecord
  # include ActiveModel::Dirty
  belongs_to :project

  # has_many :bug_ticket_users, before_add: :set_btu_flag, after_remove: :set_btu_flag
  has_many :bug_ticket_users
  has_many :users, through: :bug_ticket_users

  # after_save :reset_btu


  has_one_attached :main_image

  validates :bug_behavior, presence: true, length: { in: 50..1250 }
  validates :environment, presence: true, length: { in: 50..1250 }
  validates :status, presence: true
  validates :priority, presence: true
  validates :owner, presence: true
  validates :project_id, presence: true
  validate :acceptable_image

  has_paper_trail on: %i[create update]

  scope :filter_by_support_user, ->(support_user_ids_arr) { joins(:users).where(users: { id: support_user_ids_arr }) }


  def acceptable_image
    return unless main_image.attached?

    errors.add(:main_image, 'is too big') unless main_image.byte_size <= 5.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    errors.add(:main_image, 'must be a JPEG or PNG') unless acceptable_types.include?(main_image.content_type)
  end

end

app/controllers/bug_tickets_controller.rb
# frozen_string_literal: true

class BugTicketsController < ApplicationController
  before_action :set_bug_ticket, only: %i[show edit update destroy versions]
  before_action :authenticate_user!

  # GET /bug_tickets or /bug_tickets.json
  def index
    if current_user.role == "lead" || current_user.admin
      @q = BugTicket.ransack(params[:q])
      @bug_tickets = BugTicket.all
      @bug_tickets_search = @q.result(distinct: true)
    elsif current_user.role == "support"
      @support_bug_tickets = BugTicket.filter_by_support_user(current_user.id)
      @q = @support_bug_tickets.ransack(params[:q])
      @bug_tickets_search = @q.result(distinct: true)
    else
      @user_bug_tickets = BugTicket.where(owner: current_user.email)
      @q = @user_bug_tickets.ransack(params[:q])
      @bug_tickets_search = @q.result(distinct: true)
    end
  end

  # GET /bug_tickets/1 or /bug_tickets/1.json
  def show
    @bug_tickets = @bug_ticket.versions
  end

  # GET /bug_tickets/new
  def new
    @bug_ticket = BugTicket.new

    @user = current_user

    @users_support = User.all.select { |u| u.role != 'user' }

    @bug_ticket_user = @bug_ticket.bug_ticket_users.build

    @project_options = Project.all.map { |m| [ m.title, m.id]}

    respond_to do |format|
      format.html
    end
  end

  # GET /bug_tickets/1/edit
  def edit
    @bug_tickets = @bug_ticket.versions
    @bug_ticket.owner = current_user.email
    @project_options = Project.all.map { |m| [ m.title, m.id]}
    @users_support = User.all.select { |u| u.role != 'user' }
  end

  # POST /bug_tickets or /bug_tickets.json
  def create
    @bug_ticket = BugTicket.new(bug_ticket_params)
    @bug_ticket.owner = current_user.email
    @users_support = User.all.select { |u| u.role != 'user' }
    if current_user.role != 'user'
      params[:users][:id].each do |user|
        @bug_ticket.bug_ticket_users.build(user_id: user) unless user.empty?
      end
    end
    
    respond_to do |format|
      if @bug_ticket.save
        format.html { redirect_to bug_tickets_path, notice: 'Bug ticket was successfully created.' }
        format.json { render :show, status: :created, location: @bug_ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bug_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bug_tickets/1 or /bug_tickets/1.json
  def update
    @users_support = User.all.select { |u| u.role != 'user' }
    if current_user.role != 'user'
      @bug_ticket.bug_ticket_users.clear
      params[:users][:id].each do |user|
        @bug_ticket.bug_ticket_users.build(user_id: user) unless user.empty?
      end
    end
    respond_to do |format|
      if @bug_ticket.update(bug_ticket_params)
        format.html { redirect_to @bug_ticket, notice: 'Bug ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug_ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bug_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_tickets/1 or /bug_tickets/1.json
  def destroy
    @bug_ticket.destroy
    respond_to do |format|
      format.html { redirect_to bug_tickets_url, notice: 'Bug ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bug_ticket
    @bug_ticket = BugTicket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bug_ticket_params
    params.require(:bug_ticket).permit(:bug_behavior, :environment, :status, :priority, :owner, :comment, :category, :main_image, :project_id)
  end
end

app/helpers/bug_tickets_helper.rb
# frozen_string_literal: true

module BugTicketsHelper
end

app/views/bug_tickets/_bug_ticket.html.erb
<% unless bug_ticket.try(:event) && bug_ticket.event == "create" %>
    <tr>
      <td><%= bug_ticket.try(:reify) ? bug_ticket.reify.updated_at : bug_ticket.updated_at%></td>
      <td>
        <%= User.find(bug_ticket.paper_trail_originator).email.humanize %>,
        <br>
        <%= User.find(bug_ticket.paper_trail_originator).role.humanize %>
      </td>
      
      <td>
        <p>
          <strong>Status:</strong>
          <%= bug_ticket.try(:reify) ? bug_ticket.reify.status.humanize : bug_ticket.status.humanize %>
        </p>

        <p>
          <strong>Priority:</strong>
          <%= bug_ticket.try(:reify) ? bug_ticket.reify.priority.humanize  : bug_ticket.priority.humanize %>
        </p>

        <p>
          <strong>Ticket Reporter:</strong>
          <%= bug_ticket.try(:reify) ? bug_ticket.reify.owner.capitalize : bug_ticket.owner.capitalize %>
        </p>

        <p>
          <strong>Comment:</strong>
          

        <% if bug_ticket.reify.comment.nil? || bug_ticket.reify.comment =="" %>
          <%= "#{'None'}" %>
        <% else %>
          <%= bug_ticket.reify.comment %>
        <% end %>
        </p>
      </td>
    </tr>
  
<% end %>

app/views/bug_tickets/_form.html.erb
<%= form_with(model: bug_ticket) do |form| %>
  <% if bug_ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug_ticket.errors.count, "error") %> prohibited this bug_ticket from being saved:</h2>

      <ul>
        <% bug_ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<table>

  <% if current_user.role == "user" && !@bug_ticket.id %>
  
  <div class="field">
    <tr>
      <td> <%= form.label :main_image, "Image" %></td>
      <td> <%= form.file_field :main_image %></td>
    </tr>
  </div>
  
  <div class="field">
    <tr>
      <td><%= form.label :project_id%></td>
      <td><%= form.select(:project_id, 
      @project_options,
      {
        selected: form.object.project_id || "",
        disabled: "",
        prompt: 'Select Project'
      },
      :required => "true") %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
      <td><%= form.label :category %></td>
      <td><%= form.select :category, [['Bugs/Errors', 'bug'], ['Training/Document Requests', 'training_documents'], ['Feature Requests', 'feature_requests'], ['Other', 'other']], {:selected => @bug_ticket.category} %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
      <td><%= form.label :priority %></td>
      <td><%= form.select :priority, [['Low', 'low'], ['Medium', 'medium'], ['High', 'high'], ['Urgent', 'urgent']], {:selected => @bug_ticket.priority} %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
      <td><%= form.label :bug_behavior %></td>
      <td><%= form.text_area :bug_behavior %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
      <td><%= form.label :environment %></td>
      <td><%= form.text_area :environment %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
      <td><%= form.label :comment %></td>
      <td><%= form.text_area :comment, value: "" %></td>
    </tr>
  </div>
  <% end %>

  <% if current_user.role == "user" && @bug_ticket.id %>
    <div class="field">
      <tr>
        <td><%= form.label :comment %></td>
        <td><%= form.text_area :comment, value: "" %></td>
      </tr>
    </div>

    <% fields_for(@bug_ticket_user) do |btu| %>
      <div class="field">
        <tr>
          <td><% btu.label "Assign Support" %></td>
          <td><% collection_select(:users, :id, @users_support, :id, :email, {:selected => @bug_ticket.users.ids}, {:multiple => true}) %></td>
        </tr>
      </div>
    <% end %>
  <% end %>


  <% if current_user.role == "support" %>
    <div class="field">
      <tr>
        <td><%= form.label :category %></td>
        <td><%= form.select :category, [['Bugs/Errors', 'bug'], ['Training/Document Requests', 'training_documents'], ['Feature Requests', 'feature_requests'], ['Other', 'other']], {:selected => @bug_ticket.category} %></td>
      </tr>
    </div>

    <div class="field">
      <tr>
        <td><%= form.label :priority %></td>
        <td><%= form.select :priority, [['Low', 'low'], ['Medium', 'medium'], ['High', 'high'], ['Urgent', 'urgent']], {:selected => @bug_ticket.priority} %></td>
      </tr>
    </div>

    <div class="field">
        <tr>
          <td><%= form.label :status %></td>
          <td><%= form.select :status, [['In Progress', 'in_progress'],  ['Request Review', 'request_review'], ['Additional Info Required', 'additional_info']], {:selected => @bug_ticket.status} %></td>
        </tr>
      </div>

    <div class="field">
      <tr>
        <td><%= form.label :comment %></td>
        <td><%= form.text_area :comment, value: "" %></td>
      </tr>
    </div>

    <%= fields_for(@bug_ticket_user) do |btu| %>
      <div class="field">
        <tr>
          <td><%= btu.label "Assign Support" %></td>
          <td><%= collection_select(:users, :id, @users_support, :id, :email, {:selected => @bug_ticket.users.ids}, {:multiple => true}) %></td>
        </tr>
      </div>
    <% end %>
  <% end %>


  <% if current_user && current_user.role == "lead" || current_user.admin %>

    <div class="field">
      <tr>
        <td><%= form.label :status %></td>
        <td><%= form.select :status, [['Open', 'open'], ['Pending', 'pending'], ['In Progress', 'in_progress'], ['Request Review', 'request_review'], ['Additional Info Required', 'additional_info'], ['In Review', 'in_review'], ['Rejected', 'rejected'], ['Closed', 'closed']], {:selected => @bug_ticket.status} %></td>
      </tr>
    </div>
    
    <div class="field">
      <tr>
        <td><%= form.label :comment %></td>
        <td><%= form.text_area :comment, value: "" %></td>
      </tr>
    </div>

  <%= fields_for(@bug_ticket_user) do |btu| %>
    <div class="field">
      <tr>
        <td><%= btu.label "Assign Support" %></td>
        <td><%= collection_select(:users, :id, @users_support, :id, :email, {:selected => @bug_ticket.users.ids}, {:multiple => true}) %></td>
      </tr>
    </div>
    <% end %>
  <% end %>
  <div class="actions">
    <tr>
      <td colspan="2"><%= form.submit %></td>
    </tr>
  </div>
</table>

<% end %>

<%# 

Open: Not yet assigned
Pending: Assigned but not started
In Progress: Started working on ticket
Request Review: Ticket to be reviewed
Additional Info Required: Needs more info from ticket user
In Review: Currently being reviewed
Rejected: Switch to In Progress and start again
Completed: Finished ticket and closed out

%>

app/views/bug_tickets/_results.html.erb
<h3>Open Tickets</h3>
<% if bug_tickets.where.not(status: "closed").any? %>
  <table>
    <thead>
      <tr>
        <th>Last Update</th>
        <th>Created On</th>
        <th>Priority</th>
        <th>Bug Behavior</th>
        <th>Environment</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% bug_tickets.where.not(status: "closed").reverse.each do |bug_ticket| %>
        <tr>
          <td><%= bug_ticket.updated_at %></td>
          <td><%= bug_ticket.created_at %></td>
          <td><%= bug_ticket.priority.humanize %></td>
          <td><%= bug_ticket.bug_behavior %></td>
          <td><%= bug_ticket.environment %></td>
          <td><%= link_to 'Show', bug_ticket %></td>
          <% if current_user.role == "lead" || current_user.admin %>
            <td><%= link_to 'Edit', edit_bug_ticket_path(bug_ticket) %></td>
          <% elsif current_user.role == "support" %>
            <td><%= link_to 'Update/Comment', edit_bug_ticket_path(bug_ticket) %></td>
          <% else %>
            <td><%= link_to 'Comment', edit_bug_ticket_path(bug_ticket) %></td>
          <% end %>
          <% if current_user.admin? %>
            <td><%= link_to 'Destroy', bug_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No assigned tickets</p>
<% end %>

app/views/bug_tickets/_ticket.html.erb
<h3>Open Tickets</h3>
<% if @bug_tickets.where(status: "Open").any? %>
  <table>
    <thead>
      <tr>
        <th>Bug Behavior</th>
        <th>Environment</th>
        <th>Status</th>
        <th>Priority</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @bug_tickets.where(status: "Open").each do |bug_ticket| %>
        <tr>
          <td><%= bug_ticket.bug_behavior %></td>
          <td><%= bug_ticket.environment %></td>
          <td><%= bug_ticket.status %></td>
          <td><%= bug_ticket.priority %></td>
          <td><%= link_to 'Show', bug_ticket %></td>
          <% if current_user.role != "user" %>
            <td><%= link_to 'Edit', edit_bug_ticket_path(bug_ticket) %></td>
          <% end %>
          <% if current_user.admin? %>
            <td><%= link_to 'Destroy', bug_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No assigned tickets</p>
<% end %>

<br>

<h3>Closed Tickets</h3>
<% if @bug_tickets.where(status: "Closed").any? %>
  <table>
    <thead>
      <tr>
        <th>Bug Behavior</th>
        <th>Environment</th>
        <th>Status</th>
        <th>Priority</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @bug_tickets.where(status: "Closed").each do |bug_ticket| %>
        <tr>
          <td><%= bug_ticket.bug_behavior %></td>
          <td><%= bug_ticket.environment %></td>
          <td><%= bug_ticket.status %></td>
          <td><%= bug_ticket.priority %></td>
          <td><%= link_to 'Show', bug_ticket %></td>
          <% if current_user.role != "user" %>
            <td><%= link_to 'Edit', edit_bug_ticket_path(bug_ticket) %></td>
          <% end %>
          <% if current_user.admin? %>
            <td><%= link_to 'Destroy', bug_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <p>No closed tickets</p>
  <% end %>

app/views/bug_tickets/_tickets.html.erb
<h3>Open Tickets</h3>
<% if bug_tickets.where.not(status: "closed").any? %>
  <table>
    <thead>
      <tr>
        <th>Last Update</th>
        <th>Created On</th>
        <th>Priority</th>
        <th>Bug Behavior</th>
        <th>Environment</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% bug_tickets.where.not(status: "closed").reverse.each do |bug_ticket| %>
        <tr>
          <td><%= bug_ticket.updated_at %></td>
          <td><%= bug_ticket.created_at %></td>
          <td><%= bug_ticket.priority.humanize %></td>
          <td><%= bug_ticket.bug_behavior %></td>
          <td><%= bug_ticket.environment %></td>
          <td><%= link_to 'Show', bug_ticket %></td>
          <% if current_user.role == "lead" || current_user.admin %>
            <td><%= link_to 'Edit', edit_bug_ticket_path(bug_ticket) %></td>
          <% elsif current_user.role == "support" %>
            <td><%= link_to 'Update/Comment', edit_bug_ticket_path(bug_ticket) %></td>
          <% else %>
            <td><%= link_to 'Comment', edit_bug_ticket_path(bug_ticket) %></td>
          <% end %>
          <% if current_user.admin? %>
            <td><%= link_to 'Destroy', bug_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No assigned tickets</p>
<% end %>

<br>

<h3>Closed Tickets</h3>
<% if bug_tickets.where(status: "closed").any? %>
  <table>
    <thead>
      <tr>
        <th>Last Updated</th>
        <th>Priority</th>
        <th>Bug Behavior</th>
        <th>Environment</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% bug_tickets.where(status: "closed").reverse.each do |bug_ticket| %>
        <tr>
          <td><%= bug_ticket.updated_at %></td>
          <td><%= bug_ticket.priority.humanize %></td>
          <td><%= bug_ticket.bug_behavior %></td>
          <td><%= bug_ticket.environment %></td>
          <td><%= link_to 'Show', bug_ticket %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_bug_ticket_path(bug_ticket) %></td>
            <td><%= link_to 'Destroy', bug_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <p>No closed tickets</p>
  <% end %>

app/views/bug_tickets/edit.html.erb
<div class="container overflow-auto overflow-size">

<h1>Editing Bug Ticket</h1>

<h3>Project: <%= Project.find(@bug_ticket.project_id).title %></h3> 
<h3>Description: <%= Project.find(@bug_ticket.project_id).description %></h3> 

<p>Bug Environment: <%= @bug_ticket.environment %></p>
<p>Bug Behavior: <%= @bug_ticket.bug_behavior %></p>

<p>
  <strong>Technical Support Assigned:</strong>
  <br />
  <% if @bug_ticket.users.any?  %>
    <% @bug_ticket.users.each do |user| %>
      <%= user.email %>
      <br />
    <% end %>
  <% elsif @bug_ticket.priority == "high" %>
      <p>Please wait between 1-2 hours for someone to be assigned.</p>
  <% elsif @bug_ticket.priority == "urgent" %>
      <p>Please wait between 1-2 hours for someone to be assigned. If it requires immediate attention, please contact the IT desk.</p>
  <% else %>
      <p>"Please wait between 4-8 hours for someone to be assigned."
  <% end %>
  <p>
    <strong>Last Updated:</strong>
    <%= @bug_ticket.updated_at %>
  </p>
</p>

<% if @bug_ticket.main_image.attached? %>
      <p>
        <strong>Image:</strong>
        <div>
          <%= image_tag @bug_ticket.main_image %>
        </div>
      </p>
<% end %>

<%= render 'form', bug_ticket: @bug_ticket %>
<br>
<table>
  <thead>
    <th>Last Updated</th>
    <th>Modifier</th>
    <th>Changes</th>
  </thead>
  <tbody>
    <%= render partial: "bug_ticket", collection: @bug_tickets.reverse %>
  </tbody>
</table>
<%= link_to 'Show', @bug_ticket %> |
<%= link_to 'Back', bug_tickets_path %>

</div>

app/views/bug_tickets/index.html.erb
<div class="container justify-content-center overflow-auto overflow-size">
  <div class="bug-ticket-header">
    <h1>Bug Tickets</h1>
    <h5>
      <%= search_form_for @q do |form| %>
        <%= form.label :owner_or_priority_or_status_or_category_cont %>
        <%= form.search_field :owner_or_priority_or_status_or_category_cont %>

        <%= form.submit %>
      <% end %>
    </h5>
  </div>
  <br>
  <%= render "results", bug_tickets: @bug_tickets_search %>
  <% if current_user.role == "user"%>
    <%= render "tickets", bug_tickets: @user_bug_tickets %>
  <% elsif current_user.role == "support" %>
    <%= render "tickets", bug_tickets: @support_bug_tickets %>
  <% else %>
    <%= render "tickets", bug_tickets: @bug_tickets %>
  <% end %>
  <br>
  <% if current_user.role == "user" %>
    <%= link_to 'New Bug Ticket', new_bug_ticket_path %>
  <% end %>
</div>

app/views/bug_tickets/new.html.erb
<h1>New Bug Ticket</h1>

<%= render 'form', bug_ticket: @bug_ticket %>

<%= link_to 'Back', bug_tickets_path %>

app/views/bug_tickets/show.html.erb
<div class="container justify-content-center overflow-auto overflow-size">
<h1>Ticket Log</h1>

<table>
  <thead>
    <tr>
      <th>Current Log</th>
    </tr>
    <tr>
      <td>
        <p>
        <strong>Project Title:</strong>
        <%= Project.find(@bug_ticket.project_id).title %>
      </p>
    </tr>
    <tr>
      <td>
        <p>
        <strong>Project Description:</strong>
        <%= Project.find(@bug_ticket.project_id).description %>
      </p>
    </tr>
    <tr>
      <td>
        <p>
        <strong>Created On:</strong>
        <%= @bug_ticket.created_at %>
      </p>

      <p>
        <strong>Bug Behavior:</strong>
        <%= @bug_ticket.bug_behavior %>
      </p>

      <p>
        <strong>Environment:</strong>
        <%= @bug_ticket.environment %>
      </p>

      <p>
        <strong>Status:</strong>
        <%= @bug_ticket.status.humanize  %>
      </p>

      <p>
        <strong>Priority:</strong>
        <%= @bug_ticket.priority.humanize  %>
      </p>

      <p>
        <strong>Ticket Reporter:</strong>
        <%= @bug_ticket.owner.humanize  %>
      </p>

      <p>
        <strong>Technical Support Assigned:</strong>
        <br />
        <% if @bug_ticket.users.any?  %>
          <% @bug_ticket.users.each do |user| %>
            <%= user.email %>
            <br />
          <% end %>
        <% elsif @bug_ticket.priority == "high" %>
            <p>Please wait between 1-2 hours for someone to be assigned.</p>
        <% elsif @bug_ticket.priority == "urgent" %>
            <p>Please wait between 1-2 hours for someone to be assigned. If it requires immediate attention, please contact the IT desk.</p>
        <% else %>
            <p>"Please wait between 4-8 hours for someone to be assigned."
        <% end %>
        <p>
          <strong>Last Updated:</strong>
          <%= @bug_ticket.updated_at %>
        </p>
      </p>

      <% if @bug_ticket.main_image.attached? %>
      <p>
        <strong>Image:</strong>
        <div>
          <%= image_tag @bug_ticket.main_image %>
        </div>
      </p>
      <% end %>
      </td>
    </tr>
    <% if @bug_ticket.comment.nil? || @bug_ticket.comment != "" %>
    <tr>
      <td>
        <p>
          <strong>Support:</strong>
          <%= User.find(@bug_ticket.versions.last.whodunnit).email.capitalize %>
        </p>
        <p>
          <strong>Current Comment:</strong>
          <%= @bug_ticket.comment %>
        </p>
      </td>
    </tr>
    <% end %>
  </thead>
</table>
<br>
<table>
  <thead>
    <th>Last Updated</th>
    <th>Modifier</th>
    <th>Changes</th>
  </thead>
  <tbody>
    <%= render partial: "bug_ticket", collection: @bug_tickets.reverse %>
  </tbody>
</table>
<br>
<%= link_to 'Back', bug_tickets_path %>
</div>