config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects
  resources :users, only: %i[index edit destroy update]
  resources :bug_tickets do
    member do
      get 'versions', to: 'bug_tickets#versions'
    end
  end

  root to: 'welcome#home'

  get 'welcome/home'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bug Off! (Bugtracker)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag '/app/javascript/stylesheets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <div class="row">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Bug Off!</span>
                    </a>
                    <%# <div class="d-flex align-items-center">
                        
                    </div> %>
                </div>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <a href="/" class="nav-link align-middle px-0">
                                <%= icon("house", class: "text-success") %> <span class="ms-1 d-none d-sm-inline">Dashboard Home</span>
                            </a>
                        </li>
                        <% if current_user.admin %>
                        <li>
                            <a href="/users/" class="nav-link align-middle px-0">
                            <%# <a href="#subdmenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle"> %>
                                <%= icon("people", class: "text-success") %> <span class="ms-1 d-none d-sm-inline">Manage Accounts</span> 
                            </a>
                            <%# <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Users</span></a>
                                </li>
                                <li>
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Support</span></a>
                                </li>
                                <li>
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Lead</span></a>
                                </li>
                                <li>
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">All</span></a>
                                </li>
                            </ul> %>
                        </li>
                        <% end %>
                        
                        <li>
                            <a href="/projects/" class="nav-link px-0 align-middle">
                                <%= icon("option", class: "text-success") %> <span class="ms-1 d-none d-sm-inline">Projects</span></a>
                        </li>
                        <li>
                            <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                                <%= icon("alt", class: "text-success") %> <span class="ms-1 d-none d-sm-inline">Tickets</span></a>
                            <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                                <li class="w-100">
                                    <%# <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Open</span> 1</a> %>
                                    <%= link_to 'Bug tickets', bug_tickets_path, class: "nav-link px-0" %>
                                </li>
                                <li>
                                    <%# <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Closed</span> 2</a> %>
                                    <%# <%= link_to 'Bug tickets', bug_tickets_path, class: "nav-link px-0" %>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <hr>
                    <%if current_user %>
                    <div class="dropdown pb-4">
                        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <%# <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle"> %>
                            <span class="d-none d-sm-inline mx-1"><%= current_user.email.capitalize %> | <%= current_user.role.humanize %></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                            <li><%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><%= link_to "Sign Out", users_sign_out_path, class: "dropdown-item"  %></li>
                        </ul>
                    </div>
                    <% end %>
            <% end %>
            </div>
        </div>
        <div class="col py-3 demo-wrap">
            <%# <h3>Left Sidebar with Submenus</h3>
            <p class="lead"> An example 2-level sidebar with collasible menu items. The menu functions like an "accordion" where only a single menu is be open at a time. While the sidebar itself is not toggle-able, it does responsively shrink in width on smaller screens.</p>
            <ul class="list-unstyled">
                <li>
                    <h5>Responsive</h5> shrinks in width, hides text labels and collapses to icons only on mobile
                </li>
            </ul> %>
            <div class="demo-content">
            <%= render 'layouts/alerts', class: "demo-content" %>
            <%= yield %>
            </div>
        </div>
    </div>
</div>
</body>
</html>